name: Deploy to shinyapps.io

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true 

      - name: Install Packages
        run: |
          Rscript -e 'install.packages(c("rsconnect", "shiny"))'
          # Ajoutez vos autres packages ici si nécessaire, ex: "ggplot2", "dplyr"
        
      - name: Authorize and Deploy
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='${{ env.SHINYAPPS_ACCOUNT }}', token='${{ env.SHINYAPPS_TOKEN }}', secret='${{ env.SHINYAPPS_SECRET }}')"
          Rscript -e "rsconnect::deployApp('.')"
