name: Deploy to shinyapps.io

on:
  push:
    branches: [ main, master ]

jobs:
  shiny-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libgdal-dev libproj-dev libgeos-dev

      - name: Install R packages
        run: |
          install.packages(c("rsconnect", "shiny", "bslib", "dplyr", "leaflet", "readxl"), repos = "https://cran.rstudio.com/")
        shell: Rscript {0}

      - name: Authorize and Deploy Application
        env:
          ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          library(rsconnect)
          
          setAccountInfo(name = Sys.getenv("ACCOUNT"), token = Sys.getenv("TOKEN"), secret = Sys.getenv("SECRET"))
          
          rsconnect::writeManifest(appDir = ".")
          
          deployApp(appDir = ".", forceUpdate = TRUE)
        shell: Rscript {0}
